# Shift, Scale and Combine for R band - Abhiram

In [150]:
# Import various libraries and some specific functions. Note the additions relative to the previous lab.
import numpy as np
import astropy
import ccdproc
from ccdproc import CCDData, Combiner
from astropy import units as u
from astropy.visualization import SqrtStretch
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
from photutils import centroid_com, centroid_1dg, centroid_2dg
from photutils import CircularAperture
from photutils import aperture_photometry
from photutils import Background2D
from photutils import MedianBackground
from scipy.ndimage import shift
import gc
gc.enable()


C:\Users\abhir\AppData\Local\Temp/ipykernel_10972/1625610432.py:10: DeprecationWarning: `photutils.centroid_com` is a deprecated alias for `photutils.centroids.centroid_com`. Instead, please use `from photutils.centroids import centroid_com` to silence this warning.
  from photutils import centroid_com, centroid_1dg, centroid_2dg
C:\Users\abhir\AppData\Local\Temp/ipykernel_10972/1625610432.py:10: DeprecationWarning: `photutils.centroid_1dg` is a deprecated alias for `photutils.centroids.centroid_1dg`. Instead, please use `from photutils.centroids import centroid_1dg` to silence this warning.
  from photutils import centroid_com, centroid_1dg, centroid_2dg
C:\Users\abhir\AppData\Local\Temp/ipykernel_10972/1625610432.py:10: DeprecationWarning: `photutils.centroid_2dg` is a deprecated alias for `photutils.centroids.centroid_2dg`. Instead, please use `from photutils.centroids import centroid_2dg` to silence this warning.
  from photutils import centroid_com, centroid_1dg, centroid_2dg


In [125]:
images = ccdproc.ImageFileCollection(".",glob_include='proc_NGC*_R*')
#extract all the images of V-band
scim = [CCDData.read(fn, unit = "adu") for fn in images.files_filtered(PICTTYPE = 1)]
#Check if we got the correct files by printing them
for fn in images.files_filtered(PICTTYPE = 1):
    print(fn)


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
Set OBSGEO-Y to  2896022.315 from OBSGEO-[LBH].
Set OBSGEO-Z to -3889419.901 from OBSGEO-[LBH]'. [astropy.wcs.wcs]
Set OBSGEO-Y to  2896022.315 from OBSGEO-[LBH].
Set OBSGEO-Z to -3889419.901 from OBSGEO-[LBH]'.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the

INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
proc_NGC_1851_R_00003541.fits
proc_NGC_1851_R_00003544.fits
proc_NGC_1851_R_00003545.fits
proc_NGC_1851_R_00003546.fits
proc_NGC_1851_R_00003548.fits
proc_NGC_1851_R_00003575.fits
proc_NGC_1851_R_00003577.fits
proc_NGC_1851_R_00003578.fits
proc_NGC_1851_R_00003579.fits
proc_NGC_1851_R_00003581.fits
proc_NGC_1851_R_00003582.fits
proc_NGC_1851_R_00003603.fits
proc_NGC_1851_R_00003604.fits
proc_NGC_1851_R_0000

In [126]:
newname=[] #Defines a list
#Loops through all the images we have
for fn in images.files_filtered(PICTTYPE=1):
    newname.extend(["s"+fn]) #For each image name add an 's' and old corresponding name
print(newname) #prints the new names of images

['sproc_NGC_1851_R_00003541.fits', 'sproc_NGC_1851_R_00003544.fits', 'sproc_NGC_1851_R_00003545.fits', 'sproc_NGC_1851_R_00003546.fits', 'sproc_NGC_1851_R_00003548.fits', 'sproc_NGC_1851_R_00003575.fits', 'sproc_NGC_1851_R_00003577.fits', 'sproc_NGC_1851_R_00003578.fits', 'sproc_NGC_1851_R_00003579.fits', 'sproc_NGC_1851_R_00003581.fits', 'sproc_NGC_1851_R_00003582.fits', 'sproc_NGC_1851_R_00003603.fits', 'sproc_NGC_1851_R_00003604.fits', 'sproc_NGC_1851_R_00003605.fits', 'sproc_NGC_1851_R_00003606.fits', 'sproc_NGC_1851_R_00003607.fits', 'sproc_NGC_1851_R_00003608.fits', 'sproc_NGC_1851_R_00003609.fits', 'sproc_NGC_1851_R_00003610.fits', 'sproc_NGC_1851_R_00003611.fits', 'sproc_NGC_1851_R_00003612.fits']


In [97]:
temp=scim[0].copy() #make a copy of first image
temp=temp-np.ma.median(temp) #subtract the background using the median
# Determine the centroid - note the python convention for x and y can be flipped!
#get the position of the star using centroid_2dg
#locates based on a given x and y range to find the position of the bright star
#this outputs values in the range that is max-min(for example x1 will range between 0-100, as 1400-1300)
x1, y1 = centroid_2dg(temp[620:640,350:360])
#after finding the position, prints its position, but we need to add the minimum position,as
# the previous function subtracts its min value from it results
print(x1+350, y1+620)


347.05663206309754 632.684582445631


In [127]:
#scim.pop(4)
#newname.pop(4)

'sproc_NGC_1851_R_00003548.fits'

### Different method for shifting as stars at very different positions

In [137]:
xbox = 40               # comment
ybox = 40               # comment
shiftx=[]               # comment
shifty=[]               # comment 

for idx, thisimage in enumerate(scim): 

    # In the first 3 images the star is near 2030, 1370
    if idx<=3:            
        xoffset = int(340-xbox/2)   # x edge of the box 
        yoffset = int(630-ybox/2)   # comment

    # In the following images the star is near 1990, 1370
    elif 4<=idx<=9:
        xoffset = int(625-xbox/2)   # x edge of the box 
        yoffset = int(630-ybox/2)   # comment 
    elif 10<=idx:
        xoffset = int(590-xbox/2)   # x edge of the box 
        yoffset = int(550-ybox/2)   # comment 
    
    # If you had more images you could have more star positions
   # elif idx>=13 and idx<=99:
     #   xoffset = int(2345-xbox/2)   # x edge of the box 
      #  yoffset = int(1234-ybox/2)   # comment 
    
    temp = thisimage.data-np.ma.median(thisimage.data)    # comment
#    x1, y1 = centroid_2dg( temp[yoffset : yoffset + ybox, xoffset : xoffset + xbox]) # What is centroid 2dg
    x1, y1 = centroid_com( temp[yoffset : yoffset + ybox, xoffset : xoffset + xbox]) # What is centroid com
    print(x1 +xoffset, y1 + yoffset, newname[idx] , idx)
    shiftx.append(x1 + xoffset)
    shifty.append(y1 + yoffset )

print('\n\n\n') # What does this do?
print(shiftx)   # What is this?
print(shifty)   # What is this?

print('\n\n\n') # What does this do?
print(shiftx[0]-shiftx) # What does this mean?
print(shifty[0]-shifty) # What does this mean?

356.98061094613973 633.2156197605897 sproc_NGC_1851_R_00003541.fits 0
318.0949525091421 619.3376651438855 sproc_NGC_1851_R_00003544.fits 1
322.2151395016096 615.3507888302414 sproc_NGC_1851_R_00003545.fits 2
323.1569419006116 616.0925013630109 sproc_NGC_1851_R_00003546.fits 3
655.0352032063826 658.9004421005656 sproc_NGC_1851_R_00003575.fits 4
636.6463186635174 645.2780331424796 sproc_NGC_1851_R_00003577.fits 5
643.0334285923752 647.3749737999988 sproc_NGC_1851_R_00003578.fits 6
637.4037719590766 642.3691933514536 sproc_NGC_1851_R_00003579.fits 7
628.0725532067901 635.4575657493933 sproc_NGC_1851_R_00003581.fits 8
630.1656138534737 632.4384750253239 sproc_NGC_1851_R_00003582.fits 9
591.5506946623885 566.496314582285 sproc_NGC_1851_R_00003603.fits 10
593.2963086033144 566.0194709629802 sproc_NGC_1851_R_00003604.fits 11
596.4930534000199 566.1234005467197 sproc_NGC_1851_R_00003605.fits 12
591.9424342293474 564.9855071278783 sproc_NGC_1851_R_00003606.fits 13
587.0301945530293 560.95166782

In [15]:
xoffset = 220 # x edge of the box
yoffset = 630 # y edge of the box
xbox = 20 # x size of the box
ybox = 20 # y size of the box
shiftx=[] # list of x shift amounts
shifty=[] # list of y shift amounts
for idx, thisimage in enumerate(scim):
    temp= thisimage.copy() #make a copy of image first
    temp= temp-np.ma.median(temp) #subtract the background using the median
    #determining the centeroid like previous task
    x1, y1 = centroid_2dg( temp[yoffset : yoffset + ybox, xoffset : xoffset + xbox])
    #prints positions of the stars
    print(x1 +xoffset, y1 + yoffset )
    shiftx.append(x1 + xoffset) #add x-pos to shift x list
    shifty.append(y1 + yoffset) #add y-pos to shift y list
print(shiftx) # x pixel Positions of the same star in all images
print(shifty) # y pixel Positions of the same star in all images
#Negative = left/down, postive = right/up
print(shiftx[0]-shiftx) # prints the x-pixel amount that the image needs to be shifted by when compared to first image
print(shifty[0]-shifty) # print

223.5137978003573 638.9430967138029


231.23649100641035 642.2487558173717


232.6573186024215 648.3832015802067


229.25387203202436 642.5325165649871
[223.5137978003573, 231.23649100641035, 232.6573186024215, 229.25387203202436]
[638.9430967138029, 642.2487558173717, 648.3832015802067, 642.5325165649871]
[ 0.         -7.72269321 -9.1435208  -5.74007423]
[ 0.         -3.3056591  -9.44010487 -3.58941985]


In [138]:
shifts=[] #define the list of shifts
#iterate through all the shift positions then subtract them from first image
#finally, set them as tuples of x and y shift values and put them into shifts list
for i in range(len(shiftx)):
    shifts.append(((np.rint(shiftx[0]-shiftx[i])),np.rint(shifty[0]-shifty[i])))
print(shifts)

[(0.0, 0.0), (39.0, 14.0), (35.0, 18.0), (34.0, 17.0), (-298.0, -26.0), (-280.0, -12.0), (-286.0, -14.0), (-280.0, -9.0), (-271.0, -2.0), (-273.0, 1.0), (-235.0, 67.0), (-236.0, 67.0), (-240.0, 67.0), (-235.0, 68.0), (-230.0, 72.0), (-234.0, 75.0), (-237.0, 75.0), (-231.0, 78.0), (-228.0, 82.0), (-231.0, 85.0)]


xoffset = 1340 # x edge of the box
yoffset = 730 # y edge of the box
xbox = 100 # x size of the box
ybox = 100 # y size of the box
shiftx=[] # list of x shift amounts
shifty=[] # list of y shift amounts
# What is this code doing?
# iterating through each image and shifting by the values obtained in the previous task.
for idx, thisimage in enumerate(scim):
    yxshifts=(shifts[idx][1], shifts[idx][0]) # Note the y-x convention being used hereand in the following command.
    temp = shift(scim[idx], yxshifts, order=0, mode='constant', cval=-1000) #shifting the images
    temp=temp-np.ma.median(temp) #subtracting the median
    # What is this code doing?
    #getting the new positions of the shifted images
    x1, y1 = centroid_2dg(temp[yoffset:yoffset+ybox,xoffset:xoffset+xbox])
    #printing new shifted values for the new images and the amounts they were shifted by
    print(x1+xoffset, y1+yoffset, shifts[idx][0], shifts[idx][1])

In [139]:
#GENERATE SHIFTS
for idx, thisimage in enumerate(scim):
    yxshifts=(shifts[idx][1], shifts[idx][0])
    temp = CCDData(shift(scim[idx], yxshifts, order=0, mode='constant', cval=-1000)-np.ma.median(scim[idx]), unit="adu")
    temp.header = scim[idx].header
    temp.write(newname[idx])

In [140]:
images = ccdproc.ImageFileCollection(".",glob_include='sproc_NGC*R*')
#extract all the shifted images
scim = [CCDData.read(fn, unit = "adu") for fn in images.files_filtered(PICTTYPE = 1)]
#Check if we got the correct files by printing them
for fn in images.files_filtered(PICTTYPE = 1):
    print(fn)


INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
Set OBSGEO-Y to  2896022.315 from OBSGEO-[LBH].
Set OBSGEO-Z to -3889419.901 from OBSGEO-[LBH]'. [astropy.wcs.wcs]
Set OBSGEO-Y to  2896022.315 from OBSGEO-[LBH].
Set OBSGEO-Z to -3889419.901 from OBSGEO-[LBH]'.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the

INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader inste

INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.
INFO:astropy:using the unit adu passed to the FITS reader instead of the unit adu in the FITS file.


INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
INFO: using the unit adu passed to the FITS reader inste

In [144]:
positions = [(226,637),(1354,739), (1086,667)] #x-y notation
apertures = CircularAperture(positions, r=20.0)
phot_table = aperture_photometry(scim[0], apertures)
print(phot_table)


 id xcenter ycenter    aperture_sum   
      pix     pix          adu        
--- ------- ------- ------------------
  1   226.0   637.0  90317.50869364257
  2  1354.0   739.0 108429.72086122203
  3  1086.0   667.0  76489.14230901567


In [145]:
#positions.append((962,360)) #add x-y position
positions.append((322,407)) #add x-y position
apertures = CircularAperture(positions, r=20.0) #get circular aperture


In [146]:
phot_table=[] #list of photometry
#for each image in scim
for idx, thisimage in enumerate(scim):
    phot_table.extend([aperture_photometry(thisimage, apertures)]) #add apertures of allthese stars in all images
    print(idx, phot_table[idx]) #print by image number then apertures


0  id xcenter ycenter    aperture_sum   
      pix     pix          adu        
--- ------- ------- ------------------
  1   226.0   637.0  90317.50869364257
  2  1354.0   739.0 108429.72086122203
  3  1086.0   667.0  76489.14230901567
  4   322.0   407.0 100278.06862122193
1  id xcenter ycenter    aperture_sum   
      pix     pix          adu        
--- ------- ------- ------------------
  1   226.0   637.0  89054.38822815768
  2  1354.0   739.0 105741.71591909576
  3  1086.0   667.0  79212.50789716034
  4   322.0   407.0  103068.5954934503
2  id xcenter ycenter    aperture_sum   
      pix     pix          adu        
--- ------- ------- ------------------
  1   226.0   637.0  92300.87257915134
  2  1354.0   739.0 107634.64839323696
  3  1086.0   667.0  76089.30492296706
  4   322.0   407.0  94442.82506553661
3  id xcenter ycenter    aperture_sum   
      pix     pix          adu        
--- ------- ------- ------------------
  1   226.0   637.0   92701.6787137003
  2  1354.0   739

In [147]:
for idx, thisimage in enumerate(scim):
    print(idx)
    print(phot_table[0]['aperture_sum']/phot_table[idx]['aperture_sum'])
    print(np.ma.median(phot_table[0]['aperture_sum']/phot_table[idx]['aperture_sum']))


0
[1. 1. 1. 1.]
1.0
1
[1.0141837  1.02542048 0.9656195  0.97292554]
0.9935546170497459
2
[0.97851197 1.00738677 1.00525484 1.06178599]
1.0063208070823328
3
[0.97428126 0.99939274 0.94278916 1.05267138]
0.986837001605532
4
[ 1.1137864  -0.28679611  1.53400201  1.2577951 ]
1.185790752780635
5
[1.51034953 1.343454   1.40471534 1.61566041]
1.4575324347826852
6
[1.33382817 1.11801107 1.25292107 1.31420421]
1.2835626403598936
7
[1.20984201 1.19717451 1.11985504 1.20165476]
1.1994146350813941
8
[1.13787194 1.06467479 1.06752481 1.17646014]
1.1026983748823547
9
[1.1183077  1.01777912 1.05116926 1.14180986]
1.0847384807348295
10
[1.34884097 1.15760244 1.24949131 1.48081471]
1.2991661374533985
11
[1.25637946 1.15888091 1.20224246 1.25062736]
1.2264349111203139
12
[1.21978368 1.08323733 1.11536685 1.25470388]
1.1675752640203905
13
[1.11929091 1.06701361 1.06461487 1.2477999 ]
1.093152258378923
14
[1.11501111 1.02541018 1.0396541  1.14024855]
1.0773326036302904
15
[1.15298418 1.04307871 1.01372925

In [149]:
#for each image find the median aperture_sum ratio
for idx, thisimage in enumerate(scim):
    m = np.ma.median(phot_table[0]['aperture_sum'] / phot_table[idx]['aperture_sum'])
    print(m)
    #scim[idx] = scim[idx].multiply(m * u.adu)
#combine the images using the average method
sci_average = ccdproc.combine(scim, method = 'average',dtype = np.float32, minmax_clip = True, minmax_clip_min = -500)
#create a new file for the combined image
sci_average.write("NGC_1851_R_average.fits")
#combine using the median combine method
sci_median = ccdproc.combine(scim, method = 'median',dtype = np.float32,minmax_clip = True, minmax_clip_min = -500)
#create a new file for the median combined image
sci_median.write("NGC_1851_R_median.fits")

sci_minmax = ccdproc.combine(scim, method = 'average', dtype = np.float32, minmax_clip = True,minmax_clip_min = -500, clip_extrema = (3,3))
#create a new file for the median combined image
sci_minmax.write("NGC_1851_R_minmax.fits")


1.0
0.9935546170497459
1.0063208070823328
0.986837001605532
1.185790752780635
1.4575324347826852
1.2835626403598936
1.1994146350813941
1.1026983748823547
1.0847384807348295
1.2991661374533985
1.2264349111203139
1.1675752640203905
1.093152258378923
1.0773326036302904
1.0553352285553195
1.0753439909568205
1.0631668341691232
1.067091478807924
1.078005208181628
